version: '3'

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - 5001:5001