apiVersion: v1

kind: Pod

metadata:
  name: podmanlearning

spec:
  containers:

  - image: localhost/learning/proxy:latest
    name: proxy
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    tty: true
    volumeMounts:
    - mountPath: /config
      name: 0f54e93aa83deed64df03caf324f4e34df5eaf65cf33dd3c351dafc7566284b4-pvc
    - mountPath: /data
      name: a9ce725c66f5828ee108283add2ed4466c13ddd85ce7b1f7038e61172d529293-pvc

  - image: localhost/learning/service1:latest
    name: service1
    ports:
    - containerPort: 5000
    resources: {}
    tty: true

  - image: localhost/learning/service2:latest
    name: service2
    ports:
    - containerPort: 5001
    resources: {}
    tty: true

  enableServiceLinks: false
  
  hostname: testpod

  restartPolicy: Always

  volumes:
  - name: 0f54e93aa83deed64df03caf324f4e34df5eaf65cf33dd3c351dafc7566284b4-pvc
    persistentVolumeClaim:
      claimName: 0f54e93aa83deed64df03caf324f4e34df5eaf65cf33dd3c351dafc7566284b4
  - name: a9ce725c66f5828ee108283add2ed4466c13ddd85ce7b1f7038e61172d529293-pvc
    persistentVolumeClaim:
      claimName: a9ce725c66f5828ee108283add2ed4466c13ddd85ce7b1f7038e61172d529293
status: {}

