apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: service1
    spec:
      containers:
        - image: service1
          name: service1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
